// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    // Extract user ID from our mock token ("mock-token-jwt-XYZ" or fallback to token itself)
    let userId = "";
    if (token.startsWith("mock-token-jwt-")) {
      userId = token.replace("mock-token-jwt-", "");
    } else {
      userId = token;
    }

    return next({
      context: {
        userId,
        claims: { sub: userId },
      },
    });
  },
);
